feat: add document load under Frontend and Mobile Monitoring
SigNoz/signoz.io pull request #1023
Opened 2024-12-05 21:25 UTC by Temidayo32

Fixes: #1009

2025-01-07 19:41 UTC, Calm-Rock requested changes

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +This documentation will cover how to use OpenTelemetry to auto-instrument your web application to collect document load data. Also, you will learn how to use SigNoz to visualize and act on the collec
```suggestion
This documentation explains how to auto-instrument your web application to collect document load data, visualize it as traces in SigNoz, and set useful alerts.
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +<Tabs>
```suggestion
<Tabs entityName="plans">
```

This was introduced recently and is needed for SaaS

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +**Here's a quick summary of what you will be doing in this guide**
```suggestion
```

Let's skip this section as it doesn't add any tangible value for a user. Once we have the table of contents working as expected, the user can use it to navigate to a particular section.

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +* Auto-Instrument a Web Application to collect Document Load Data.
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +* Send Telemetry Data to SigNoz.
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +* Setup Useful Alerts on Document Trace Data.
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +* A [SigNoz](https://signoz.io/teams/) Cloud Account.
```suggestion
```
Not needed as it is already inside the Cloud Tab

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +* A Web Application for capturing document load data.
```suggestion
* A Web Application for capturing document load data
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +
```suggestion
## Setup
```

Steps should be part of the Setup section.

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +### Step 1: Download the Sample Web Application
```suggestion
```

Since we have mentioned in the Prerequisite that the user should have a web application, this step is not needed. Make the next step as the first step.

As a rule of thumb, for documentation, we should not have sample apps as a part of the Setup steps since documentation should be agnostic of any particular application.

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +You can download and use the sample React application. If you have a web application to use, you can skip this step.
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +```bash
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +git clone https://github.com/SigNoz/sample-reactjs-app.git
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +```
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +```javascript
```suggestion
```javascript:otel-setup.js
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +In the `src` directory of your web application, create a new JavaScript file (e.g., `otel-setup.js`) and paste the code below.
Also explain what the below code will do in 1-2 lines

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +  url: `https://ingest.${REGION}.signoz.cloud:${PORT}/v1/traces`,
```suggestion
  url: `https://ingest.<region>.signoz.cloud:443/v1/traces`,
```

`443` is the port we use for cloud. Could you confirm this that you used the `443` port and comment here.

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +  headers: { 'signoz-access-token': "<SIGNOZ_INGESTION_KEY>" });
```suggestion
  headers: { 'signoz-access-token': "<your-ingestion-key>" });
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +const provider = new WebTracerProvider({ resource: new Resource({ "service.name": "<SERVICE_NAME>" }) // Set the SigNoz Cloud collector URL
```suggestion
const provider = new WebTracerProvider({ resource: new Resource({ "service.name": "<service_name>" }) // Set the SigNoz Cloud collector URL
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +Ensure to replace the placeholders for `<SERVICE_NAME>`, `<REGION>`,  `<PORT>`, and `<SIGNOZ_INGESTION_KEY>` with your actual service name, region, port, and SigNoz ingestion key, respectively.
```suggestion
- Set the `<region>` to match your SigNoz Cloud [region](https://signoz.io/docs/ingestion/signoz-cloud/overview/#endpoint)
- Replace `<your-ingestion-key>` with your SigNoz [ingestion key](https://signoz.io/docs/ingestion/signoz-cloud/keys/).
- `<service_name>` is name of your service
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +You can find your ingestion key in the following places:
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +* The mail which you received from SigNoz after signing up.
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +* Inside settings on SigNoz dashboard.
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +Depending on the choice of your region for SigNoz cloud, the ingest endpoint will vary according to this table.
```suggestion
```
Replaced with proper links in the above comment.

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +| Region | Endpoint |
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +| --- | --- |
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +| US | ingest.us.signoz.cloud:443/v1/traces |
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +| IN | ingest.in.signoz.cloud:443/v1/traces |
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +| EU | ingest.eu.signoz.cloud:443/v1/traces |
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +These are the variables you need to replace:
```suggestion
```

Replaced with proper explanation in the previous comment

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +| Placeholder | Description |
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +| --- | --- |
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +| `<SIGNOZ_INGESTION_KEY>` | Your SigNoz ingestion key |
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +| `<PORT>` | Port (default: 443) |
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +| `<REGION>` | Region for SigNoz ingestion URL |
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +
```suggestion

```
Just put a small snippet of code explaining how to import the `otel-setup.js` file into `index.js` file.

Just show the import section of the code.

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +Congratulations! You have successfully integrated OpenTelemetry Auto-instrumentation into your web application. It’s time to see the collected data.
```suggestion
You will now see your application in the **Services** section in the SigNoz sidebar.
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +Visit your running SigNoz Cloud Instance. Navigate to the **Services** section in the sidebar to view your service.
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +## Why is the Data Collected Useful?
This should be part of the overview section.
Please move this to the Overview section. Remove the heading "Why is the Data Collected Useful?"

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +Using OpenTelemetry to capture data on **document load** is useful because it allows you to monitor your application's key performance metrics. This data is essential for:
```suggestion

```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +You can create **trace-based alerts** by using the `Create an Alert` button in the **Traces** section.  Alternatively, you can directly create it from the **Alerts** section. To create and manage tra
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +
```suggestion
You can create **trace-based alerts** by using the `Create an Alert` button in the [Save View](https://signoz.io/docs/product-features/saved-view/) button at the bottom of **Traces** section.  Alternatively, you can directly create it from the **Alerts** section. To create and manage trace-based alerts, follow [this guide](https://signoz.io/docs/alerts-management/trace-based-alerts/).

In this example, we will set up an alert for `ResourceFetch`. Resource Fetch reports all the resources, including external scripts, images, style sheets, fonts, and other assets, that are required to render a webpage. Knowing the time it takes to fetch resources will be useful in taking proactive action to optimize your application using caching or other optimization strategies.
```

Add this just below the Create an Alert section

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +To create an alert, you will use the `Create an Alert` button in the **Traces** section. In this example, you will be setting up an alert for `ResourceFetch`. Resource Fetch reports all the resources
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +In the `Traces Based Alerts` page, set the `Traces` field to `service.name = <SERVICE_NAME>`  and `name = resourceFetch` . Next, set the `Y-axis units` to seconds. You can also set the `Legend Format
```suggestion
In the `Traces Based Alerts` page, set the `Traces` field to `service.name = <service_name>`  and `name = resourceFetch` . Next, set the `Y-axis units` to seconds. You can also set the `Legend Format` to `Resource Fetch`and then press the **Stage & Run Query** button.
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +Next, you will define an alert condition. Set the `Send a notification when ...`  field to read as **Send a notification when `A` is `above` the threshold `at least once` during the last `5 mins`.**
```suggestion
Define an alert condition with **Send a notification when `A` is `above` the threshold `at least once` during the last `5 mins`** and set the  `Alert Threshold` field to `10 seconds`.
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +Here, set the severity field to `critical`. Next, set the `Alert Name` field to `ResourceFetch`. Next, turn on the alert all notification channel field. Lastly, save the rule and test the notificatio
```suggestion
Set the `Severity` field to `critical`, the `Alert Name` field to `ResourceFetch`, toggle on the `Alert all the configured channels` field to alert all the notification channels. You can choose to send the alert to a particular notification channel by selecting a particular Notifcation Channel from the dropdown. Save the rule and test the notification.
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +With that, you have successfully integrated OpenTelemetry to auto-instrument your web application for collecting document load data. You have also learned how to set useful alerts on the data.
```suggestion
With this, you have successfully set up a useful alerts on your data.
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +* A [Self-Hosted](https://signoz.io/docs/install/docker/) SigNoz.
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +**Here's a quick summary of what you will be doing in this guide**
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +* Auto-Instrument a Web Application to collect Document Load Data.
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +* Send Telemetry Data to SigNoz.
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +* Setup Useful Alerts on Document Trace Data.
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +* A Web Application for capturing document load data.
```suggestion
* A Web Application for capturing document load data
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +### Step 1: Download the Sample Web Application
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +You can download and use the sample React application. If you have a web application to use, you can skip this step.
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +```bash
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +git clone https://github.com/SigNoz/sample-reactjs-app.git
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +```
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +In the `src` directory of your web application, create a new JavaScript file (e.g., `otel-setup.js`) and paste the code below.
Also explain what the below code will do in 1-2 lines

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +const provider = new WebTracerProvider({ resource: new Resource({ "service.name": "<SERVICE_NAME>" }) // Set the SigNoz Cloud collector URL
```suggestion
const provider = new WebTracerProvider({ resource: new Resource({ "service.name": "<service_name>" }) // Set the SigNoz Cloud collector URL
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +Ensure to replace the placeholders for `<SERVICE_NAME>` with your actual service name. Set a proxy in your `package.json` pointing to to the SigNoz OTLP HTTP endpoint. This is an easier temporary set
```suggestion
Set a proxy in your `package.json` pointing to to the SigNoz OTLP HTTP endpoint. This is an easier temporary setup to bypass CORS issues. You can use [this documentation](https://signoz.io/docs/userguide/otlp-http-enable-cors/) to guide you on dealing with CORS issues for a permanent setup.
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +
```suggestion
- `<service_name>` is name of your service
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +
```suggestion

```

Just put a small snippet of code explaining how to import the `otel-setup.js` file into `index.js` file.

Just show the import section of the code.

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +Congratulations! You have successfully integrated OpenTelemetry Auto-instrumentation into your web application. It’s time to see the collected data.
```suggestion
You will now see your application in the **Services** section in the SigNoz sidebar.

```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +Visit your running SigNoz Cloud Instance. Navigate to the **Services** section in the sidebar to view your service.
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +## Why is the Data Collected Useful?
```suggestion
```

As mentioned in the Cloud section comment, this should be part of the overview section and since the overview section is common for both cloud and self-host tabs, this portion can be completely removed from here.

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +You can create **trace-based alerts** by using the `Create an Alert` button in the **Traces** section.  Alternatively, you can directly create it from the **Alerts** section. To create and manage tra
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +
```suggestion
You can create **trace-based alerts** by using the `Create an Alert` button in the [Save View](https://signoz.io/docs/product-features/saved-view/) button at the bottom of **Traces** section.  Alternatively, you can directly create it from the **Alerts** section. To create and manage trace-based alerts, follow [this guide](https://signoz.io/docs/alerts-management/trace-based-alerts/).

In this example, we will set up an alert for `ResourceFetch`. Resource Fetch reports all the resources, including external scripts, images, style sheets, fonts, and other assets, that are required to render a webpage. Knowing the time it takes to fetch resources will be useful in taking proactive action to optimize your application using caching or other optimization strategies.
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +To create an alert, you will use the `Create an Alert` button in the **Traces** section. In this example, you will be setting up an alert for `ResourceFetch`. Resource Fetch reports all the resources
```suggestion
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +In the `Traces Based Alerts` page, set the `Traces` field to `service.name = <TabItem>`  and `name = resourceFetch` . Next, set the `Y-axis units` to seconds. You can also set the `Legend Format` to
```suggestion
In the `Traces Based Alerts` page, set the `Traces` field to `service.name = <service_name>`  and `name = resourceFetch` . Next, set the `Y-axis units` to seconds. You can also set the `Legend Format` to `Resource Fetch`and then press the **Stage & Run Query** button.
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +Next, you will define an alert condition. Set the `Send a notification when ...`  field to read as **Send a notification when `A` is `above` the threshold `at least once` during the last `5 mins`.**
```suggestion
Define an alert condition with **Send a notification when `A` is `above` the threshold `at least once` during the last `5 mins`** and set the  `Alert Threshold` field to `10 seconds`.
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +Here, set the severity field to `critical`. Next, set the `Alert Name` field to `ResourceFetch`. Next, turn on the alert all notification channel field. Lastly, save the rule and test the notificatio
```suggestion
Set the `Severity` field to `critical`, the `Alert Name` field to `ResourceFetch`, toggle on the `Alert all the configured channels` field to alert all the notification channels. You can choose to send the alert to a particular notification channel by selecting a particular Notifcation Channel from the dropdown. Save the rule and test the notification.
```

2025-01-07 19:41 UTC, Calm-Rock commented on data/docs/frontend-monitoring/document-load.mdx
> +With that, you have successfully integrated OpenTelemetry to auto-instrument your web application for collecting document load data. You have also learned how to set useful alerts on the data.
```suggestion
With this, you have successfully set up a useful alerts on your data.
```

2025-01-08 11:29 UTC, Temidayo32 commented on data/docs/frontend-monitoring/document-load.mdx
> +  url: `https://ingest.${REGION}.signoz.cloud:${PORT}/v1/traces`,
Yes, definitely. I used 443 port.

2025-01-10 13:23 UTC, Calm-Rock approved these changes

2025-01-10 13:24 UTC, merged