Add Quarkus Instrumentation Documentation
SigNoz/signoz.io pull request #1025
Opened 2024-12-06 15:46 UTC by Creator54

This PR adds comprehensive documentation for instrumenting Quarkus applications with OpenTelemetry and integrating with SigNoz. It includes setup instructions for VM, Kubernetes, and Windows environments, along with configuration and troubleshooting guidance.

**Key Changes:**

- Created opentelemetry-quarkus.mdx with Quarkus instrumentation steps.
- Updated docsSideNav.ts to include Quarkus in the navigation menu.
- Added relevant images for Quarkus documentation.
- Modified next.config.js to set up redirects for Quarkus docs.

**Closes Issue:** #996

2024-12-13 14:57 UTC, Calm-Rock approved these changes

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +This document contains instructions on how to set up OpenTelemetry instrumentation in your Quarkus applications. OpenTelemetry, also known as OTel for short, is an open source observability framework
```suggestion
This document contains instructions on how to set up OpenTelemetry instrumentation in your Quarkus applications and view your application traces in SigNoz.  
```

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +<figure data-zoomable align='center'>
Let's remove this Figure.

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +After completing this guide, you will have:
Let's remove these pointers as well.

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +After completing this guide, you will have:
```suggestion
```

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +- A Quarkus application sending traces, metrics, and logs to SigNoz
```suggestion
```

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +- Real-time visibility into your application's performance
```suggestion
```

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +- Ability to troubleshoot issues using distributed tracing
```suggestion
```

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +- Monitoring dashboards for your application metrics
```suggestion
```

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +Let's understand how to install and run OpenTelemetry in your Quarkus application.
```suggestion
```

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +- A Quarkus REST application with basic endpoints.
```suggestion
- A Quarkus REST application with basic endpoints
```

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +- Docker (if using Docker and Kubernetes)
Do we tell the user about Docker instructions? If not then, we should remove this as well.

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +- OpenTelemetry extension added to your project:
This should not be a Prerequisite. Instead, this should be the first step under configuration steps.

These three commands should be in 3 tabs - Quarkus CLI, Maven and Gradle

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +## Requirements
```suggestion
## Prerequisite
```

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> + - Update `application.properties`
We should explain why the user should update this file and what these updates are doing **in brief**.

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +```properties:src/main/resources/application.properties
We don't want the user to collect logs and metrics primarily - please update this configuration file accordingly.

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +  export OTEL_EXPORTER_OTLP_HEADERS="signoz-access-token=SIGNOZ_INGESTION_KEY"
```suggestion
  export OTEL_EXPORTER_OTLP_HEADERS="signoz-ingestion-key=SIGNOZ_INGESTION_KEY"
```

We have stopped using signoz-access-token for ingestion keys

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +- `SIGNOZ_INGESTION_KEY` is the API token provided by SigNoz. You can find your ingestion key from SigNoz cloud account details sent on your email.
```suggestion
- `SIGNOZ_INGESTION_KEY` is the [Ingestion Key provided by SigNoz](https://signoz.io/docs/ingestion/signoz-cloud/keys/). 
```

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +2. Build and run your application:
Put the three options in this step under 3 tabs

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +- `SIGNOZ_INGESTION_KEY` is the API token provided by SigNoz. You can find your ingestion key from SigNoz cloud account details sent on your email.
```suggestion
- `SIGNOZ_INGESTION_KEY` is the [Ingestion Key provided by SigNoz](https://signoz.io/docs/ingestion/signoz-cloud/keys/). 
```

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +- `SIGNOZ_INGESTION_KEY` is the API token provided by SigNoz. You can find your ingestion key from SigNoz cloud account details sent on your email.
```suggestion
- `SIGNOZ_INGESTION_KEY` is the [Ingestion Key provided by SigNoz](https://signoz.io/docs/ingestion/signoz-cloud/keys/). 
```

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +4. Check logs in the Logs tab
Let's remove this image since logs are in an experimental state.

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +- Ensure your application can reach the SigNoz endpoint
How do user ensure this ?

2024-12-13 14:57 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +## Sample Application
Lets move the Sample Application section above the Troubleshooting section

2024-12-13 14:59 UTC, Calm-Rock requested changes

2024-12-13 14:59 UTC, Calm-Rock commented on next.config.js
> +        {
We can skip this redirect and instead name the mdx file `id` as `opentelemetry-quarkus`

2024-12-13 15:18 UTC, Calm-Rock requested changes

2024-12-13 15:18 UTC, Calm-Rock commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +<TabItem value="cloud" label="SigNoz Cloud" default>
Just below this tab, let's add an Info admonition saying:

<Admonition type="info">
If you haven't already, signup for [SigNoz Cloud](https://signoz.io/teams/).
</Admonition>

2024-12-14 05:46 UTC, Creator54 commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +- Docker (if using Docker and Kubernetes)
yes

2024-12-14 16:44 UTC, Creator54 commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> +- Ensure your application can reach the SigNoz endpoint
added steps to check for logs.

2024-12-14 16:45 UTC, Creator54 commented on data/docs/instrumentation/opentelemetry-quarkus.mdx
> + - Update `application.properties`
added comments

2024-12-17 05:20 UTC, Calm-Rock approved these changes

2024-12-17 05:24 UTC, merged

2024-12-17 05:25 UTC, Calm-Rock commented
Good work @Creator54!