Add Documentation for Sending Node.js Pino Logs to SigNoz
SigNoz/signoz.io pull request #1033
Opened 2024-12-07 23:31 UTC by animeshd9

This PR addresses issue #1010 by adding a new documentation file that explains how to send logs from Node.js applications using **Pino** directly to SigNoz, without requiring OpenTelemetry collectors. The documentation covers setups for both **SigNoz Cloud** and **Self-hosted SigNoz**.

## Changes Introduced

1. **New Documentation File**:
   - Created a file named `nodejs-pino-logs.mdx`.
   - Added metadata with the ID `nodejs-pino-logs`.

2. **Side Navigation Update**:
   - Added a new dropdown called `NodeJS` under the **Send Logs to SigNoz** section in **Logs Management**.
   - Included a sub-item titled `Pino` pointing to the new documentation file.

3. **Content**:
   - Provided detailed instructions for configuring Node.js Pino logs to send data to SigNoz.
   - Included specific configurations for both SigNoz Cloud and Self-hosted SigNoz setups.
   - Referenced relevant external resources, such as the [SigNoz Blog](https://signoz.io/blog/) and the [Pino OpenTelemetry Transport](https://github.com/pinojs/pino-transport-opentelemetry).

## Verification

- Verified the file placement within the **Logs Management** section of the documentation.
- Ensured the metadata and structure comply with the project’s documentation standards.

2025-01-06 12:35 UTC, Calm-Rock requested changes

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +This guide demonstrates how to configure Pino to send logs directly to SigNoz Cloud or Self-hosted SigNoz without using OpenTelemetry collectors. Following this documentation will enable you to strea
```suggestion
This document explains how to configure Pino to stream Node.js application logs directly to your SigNoz dashboard.
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +**Here's a quick summary of what we will be doing in this guide**
```suggestion
```

Lets remove this section.

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +* Create Node.js application with pino logger
```suggestion
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +* Configure pino logger to send logs to SigNoz Cloud
```suggestion
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +* Send and Visualize the logs in SigNoz Cloud
```suggestion
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +Before starting ensure you have:
```suggestion
```

We can directly write the pre-requisites since this section is titled as Prerequisites

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +- A SigNoz Cloud account with active subscription
```suggestion
```

Since this is under SigNoz Cloud Tab, we can skip saying to signup for SigNoz Cloud.

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +* See [SigNoz Cloud Configuration Guide](https://signoz.io/docs/ingestion/signoz-cloud/keys/) for details on finding your ingestion URL and access token
```suggestion
```

We will mention this in the step where we are using the ingestion key.

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +- Access to your SigNoz Cloud:
```suggestion
```

We will mention this in the step where we are using the ingestion key.

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +    - Ingestion endpoint URL
```suggestion
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +    - Ingestion Key
```suggestion
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +## Required Dependencies
Let use this as Step 1 of the Setup.

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +```jsx
Just above the code block, can you explain in brief:
- What this code block will do
- Where should the user put this code block? Should they create a new file called `tracing.js` in the root directory or something else.

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +//tracing.js
Will this file work if someone is using typescript ? If yes, please mention this. If not, please create 2 tabs one for `js` and another for `ts`

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +```jsx
Just above the code block, can you explain in brief:

- What this code block will do
- If this is an example file, please mention it and explain what this example is doing.

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +Execute your application with the SigNoz access token:
```suggestion
Execute your application with OpenTelemetry Environment variables:
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +OTEL_EXPORTER_OTLP_HEADERS="signoz-access-token=your_signoz_ingestion_token" OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=https://ingest.{region}.signoz.cloud:443/v1/logs OTEL_RESOURCE_ATTRIBUTES="service.name=m
```suggestion
OTEL_EXPORTER_OTLP_HEADERS="signoz-ingestion-key=<your-ingestion-key>" OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=https://ingest.<region>.signoz.cloud:443/v1/logs OTEL_RESOURCE_ATTRIBUTES="service.name=<service_name>,service.version=1.2.3" node -r ./tracing.js app.js
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +
```suggestion
- Set the <region> to match your SigNoz Cloud [region](https://signoz.io/docs/ingestion/signoz-cloud/overview/#endpoint)
- Replace <your-ingestion-key> with your SigNoz [ingestion key](https://signoz.io/docs/ingestion/signoz-cloud/keys/).
- <service_name> is name of your service
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +## Usage Examples
What is this section doing? Is it an example?

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +After successful implementation, your logs will appear in your SigNoz Cloud dashboard where you can:
```suggestion
After successful implementation, your logs will appear in your SigNoz Logs section where you can:
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +- Monitor logs in real-time
```suggestion
- Monitor logs in [real-time](https://signoz.io/docs/product-features/logs-explorer/#live-view)
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +- Filter logs by level and custom attributes
```suggestion
- [Filter logs](https://signoz.io/docs/userguide/logs_query_builder/) by level and custom attributes
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +- Search through log contents
```suggestion
- [Search](https://signoz.io/docs/product-features/logs-explorer/#search) through log contents
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +- Create alerts based on log patterns
```suggestion
- Create [alerts based on log](https://signoz.io/docs/alerts-management/log-based-alerts/) patterns
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +*Log from SigNoz dashboard*
```suggestion
```
Caption is already added in the above image.

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +**Here's a quick summary of what we will be doing in this guide**
```suggestion
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +* Create Node.js application with pino logger
```suggestion
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +* Containerize the application
```suggestion
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +* If your using Kubernetes, create a deployment
```suggestion
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +* Send and Visualize the logs in Self-hosted SigNoz
```suggestion
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +Before starting ensure you have:
```suggestion
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +* See [Self-hosted SigNoz Configuration Guide for docker](https://signoz.io/docs/install/docker/)
```suggestion
```

Let's hyperlink this in the step where we are telling the user to use docker **if needed**

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +* Your Self-hosted SigNoz is ready
```suggestion
- Self-hosted SigNoz instance
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +* See [Self-hosted SigNoz Configuration Guide for kubernetes](https://signoz.io/docs/install/kubernetes/)
```suggestion
```

Let's hyperlink this in the step where we are telling the user to use Kubernetes **if needed**

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +## Required Dependencies
Let use this as Step 1 of the Setup.

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +```jsx
Just above the code block, can you explain in brief:
- What this code block will do
- Where should the user put this code block? Should they create a new file called `tracing.js` in the root directory or something else.

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +```jsx
Just above the code block, can you explain in brief:

- What this code block will do
- If this is an example file, please mention it and explain what this example is doing.

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +### Step 3. Containerize the application
```suggestion
```

As discussed, let's remove this section since it is not a general step.

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +### Step 2. Run with Docker
```suggestion
```
As discussed, let's remove this section since it is not a general step.

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +### Step 3. Deploy to Kubernetes (Optional)
```suggestion
```

As discussed, let's remove this section since it is not a general step.

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +## Usage Examples
Please explain what the content of this section will do.

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +After successful implementation, your logs will appear in your Self-hosted SigNoz dashboard where you can:
```suggestion
After successful implementation, your logs will appear in your SigNoz Logs Section where you can:
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +- Monitor logs in real-time
```suggestion
- Monitor logs in [real-time](https://signoz.io/docs/product-features/logs-explorer/#live-view)
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +- Filter logs by level and custom attributes
```suggestion
- [Filter logs](https://signoz.io/docs/userguide/logs_query_builder/) by level and custom attributes
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +- Search through log contents
```suggestion
- [Search](https://signoz.io/docs/product-features/logs-explorer/#search) through log contents
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +- Create alerts based on log patterns
```suggestion
-  Create [alerts based on log](https://signoz.io/docs/alerts-management/log-based-alerts/) patterns
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +Log from SigNoz dashboard
```suggestion
Node.js Pino Logs in SigNoz
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +Node.js Pino Logs
```suggestion
Node.js Pino Logs in SigNoz
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +3. Review SigNoz dashboard filters
```suggestion
3. Review SigNoz Logs Section filters
```

2025-01-06 12:35 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +3. Review SigNoz dashboard filters
```suggestion
3. Review SigNoz Logs Section filters
```

2025-01-08 17:43 UTC, animeshd9 commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +## Usage Examples
I'll add Few screenshots and explain briefly about "warn" and "error"

2025-01-10 16:12 UTC, Calm-Rock requested changes

2025-01-10 16:12 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +Add the following code to your application:
Where should this code be added and what is this code for ? Please mention this explicitly.
Ref old comment: [here](https://github.com/SigNoz/signoz-web/pull/1033#discussion_r1903634325)

2025-01-10 16:12 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +- Replace `<your-ingestion-key>` with your SigNoz [ingestion key](https://signoz.io/docs/ingestion/signoz-cloud/keys/).
```suggestion
- Replace `<your-ingestion-key>` with your SigNoz [ingestion key](https://signoz.io/docs/ingestion/signoz-cloud/keys/)
```

2025-01-10 16:12 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +## Prerequisites
```suggestion
```

2025-01-10 16:12 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/nodejs-pino-logs.mdx
> +- Self-hosted SigNoz instance
```suggestion
```

Let's remove this since we have the self-host tab, and the user should be able to understand that they need to follow these instructions if they are using Self-Hosted SigNoz.

2025-01-12 04:35 UTC, Calm-Rock approved these changes

2025-01-12 04:36 UTC, merged