OpenTelemetry Bridge for Logrus
SigNoz/signoz.io pull request #1036
Opened 2024-12-08 21:52 UTC by Quadrisheriff

2025-01-09 07:52 UTC, Calm-Rock requested changes

2025-01-09 07:52 UTC, Calm-Rock commented on constants/docsSideNav.ts
> +            label: 'OpenTelemetry Bridge for Logrus',
```suggestion
            label: 'Logrus',
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +This guide will teach you how to collect log data from [Logrus](https://github.com/sirupsen/logrus) to [SigNoz](https://signoz.io/) using the [OpenTelemetry Logrus Log Bridge (Otellogrus)](https://ww
```suggestion
This document explains how to collect log data from [Logrus](https://github.com/sirupsen/logrus) and visualise it in [SigNoz](https://signoz.io/).
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +- [Self-hosted SigNoz](https://signoz.io/docs/install/docker/) or [SigNoz cloud account](https://signoz.io/).
```suggestion
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +### Step 1: Get the sample Golang application.
```suggestion
```

Remove this step since the user will have their own golang application

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +Navigate to the `sample-golang` app root folder and run the following command to install the required dependencies.
```suggestion
Navigate to the root folder of your golang application and run the below command to install the required dependencies.
```

Also explain in a couple of lines about what these dependencies will do

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +The next step is to install all the required dependencies to implement the OpenTelemetry Logrus Log Bridge.
```suggestion
Install all the required dependencies to implement the OpenTelemetry Logrus Log Bridge. 
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +## Instrument your application with the OpenTelemetry Logrus Log Bridge
```suggestion
## Setup
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +To instrument your Go application with the OpenTelemetry Logrus Log Bridge, add the following code to your sample-golang-app `main.go` file.
```suggestion
To instrument your Go application with the OpenTelemetry Logrus Log Bridge, add the following code to your golang application `main.go` file.
```

Explain in a couple of lines, what this code is doing.

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +To add the Span and Trace ID fields to your structured logs:
```suggestion
To add the Span and Trace ID fields to your structured logs:
```
Briefly explain in a couple of lines why a user would want to add Span and Trace ID in logs

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +- Golang installed. You can download and install it from the official [Go website](https://golang.org/).
```suggestion
- A running Golang application
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +- Familiarity with [Golang Logging](https://signoz.io/guides/golang-log/).
```suggestion
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +### Step 2: Install dependencies
```suggestion
### Step 1: Install dependencies
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +### Step 3: Instrument OpenTelemetry Logrus Log Bridge in your Golang application
```suggestion
### Step 2: Instrument OpenTelemetry Logrus Log Bridge in your Golang application
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +## Inject Trace and Span ID fields to your logs
```suggestion
### Step 3 (Optional): Inject Trace and Span ID fields to your logs
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +### Step 1: Import the OpenTelemetry Trace library
```suggestion
**Import the OpenTelemetry Trace library**
```

Explicilty mentions where this code needs to be added. Clearly mention where these imports will be added.

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +```
```suggestion
```golang
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +### Step 2: Fetch the current Span and Trace ID from context with the OpenTelemetry Trace library
```suggestion
**Fetch current Span and Trace ID from context**

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +
```suggestion
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +```
```suggestion
```golang
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +   otel.SetTracerProvider(
Clearly mention where this code needs to be added. Also explain in a couple of lines what will this codeblock do.

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +### Step 3:  Create a function to add the Span and Trace ID values to your Logrus fields
```suggestion
**Create a function to add Span and Trace ID values to your Logrus fields** 
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +```
```suggestion
```golang
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +func LogrusFields(span oteltrace.Span) logrus.Fields {
Clearly mention where this code needs to be added. Also explain in a couple of lines what will this codeblock do.

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +<Tabs>
```suggestion
<Tabs entityName="plans">
```
This is needed for SaaS and was introduced after this PR was raised.

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +<TabItem value="self" label="Self-hosted SigNoz">
```suggestion
<TabItem value="self-host" label="Self-hosted SigNoz">
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +## Send Logrus logs to SigNoz
```suggestion
### Step 4: Send Logrus logs to SigNoz 
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +2. Run your Golang application with your Signoz credentials.
```suggestion
2. Run your Golang application with your SigNoz credentials
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +1. Add logs to your application.
```suggestion
1. Add logs to your application
```
Clearly explain where should this line of code be added.

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +    - `<SIGNOZ_ACCESS_TOKEN>`: Your SigNoz cloud ingestion token.
```suggestion
    - Replace `<your-ingestion-key>` with your SigNoz [ingestion key](https://signoz.io/docs/ingestion/signoz-cloud/keys/).
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +	INSECURE_MODE=false OTEL_EXPORTER_OTLP_HEADERS=signoz-access-token=<SIGNOZ_ACCESS_TOKEN> OTEL_EXPORTER_OTLP_ENDPOINT=<SIGNOZ_OPENTELEMETRY_ENDPOINT> go run main.go
```suggestion
	INSECURE_MODE=false OTEL_EXPORTER_OTLP_HEADERS=signoz-ingestion-key=<your-ingestion-key> OTEL_EXPORTER_OTLP_ENDPOINT=ingest.<region>.signoz.cloud:443 go run main.go
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +    - `<SIGNOZ_OPENTELEMETRY_ENDPOINT>`: Your SigNoz cloud ingestion URL. The value is `https://ingest.{region}.signoz.cloud:443` where `{region}` is the choice region in SigNoz cloud.
```suggestion
    - Set the `<region>` to match your SigNoz Cloud [region](https://signoz.io/docs/ingestion/signoz-cloud/overview/#endpoint)
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +
Add a final output image

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +1. Add logs to your application.
```suggestion
1. Add logs to your application
```

Clearly explain where should this line of code be added.

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +2. Run your Golang application with your Signoz credentials.
```suggestion
2. Run your Golang application with your Signoz credentials
```

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +
Please add an output image

2025-01-09 07:52 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +```
```suggestion
```golang
```

2025-01-09 18:38 UTC, Quadrisheriff commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +1. Add logs to your application.
logs can be added anywhere.

2025-01-10 13:19 UTC, Calm-Rock requested changes

2025-01-10 13:19 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +```golang
```suggestion
```go
```

2025-01-10 13:19 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +```golang
```suggestion
```go
```

2025-01-10 13:19 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +```golang
```suggestion
```go
```

2025-01-10 13:19 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +```golang
```suggestion
```go
```

2025-01-10 13:19 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +    ```golang
```suggestion
    ```go
```

2025-01-10 13:19 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +    ```golang
```suggestion
    ```go
```

2025-01-10 13:19 UTC, Calm-Rock commented on data/docs/logs-management/send-logs/logrus-to-signoz.mdx
> +    - Replace `<your-ingestion-key>` with your SigNoz [ingestion key](https://signoz.io/docs/ingestion/signoz-cloud/keys/).
```suggestion
    - Replace `<your-ingestion-key>` with your SigNoz [ingestion key](https://signoz.io/docs/ingestion/signoz-cloud/keys/)
```

2025-01-11 05:14 UTC, Calm-Rock approved these changes

2025-01-11 05:14 UTC, merged