docs: add information on how otel collector collects data
SigNoz/signoz.io pull request #267
Opened 2024-06-14 09:22 UTC by nitishfy

2024-06-19 05:28 UTC, Calm-Rock requested changes

2024-06-19 05:28 UTC, Calm-Rock commented on data/docs/userguide/send-metrics-cloud.mdx
> +Data collection in OpenTelemetry Collector is facilitated through receivers. Receivers are configured via YAML under the top-level `receivers` tag. To ensure a valid configuration, at least one recei
```suggestion
Data collection in OpenTelemetry Collector is facilitated through receivers. Receivers are configured via YAML under the top-level `receivers` section. To ensure a valid configuration, at least one receiver must be enabled.
```

[tags](https://www.javatpoint.com/yaml-tags) in YAML is something else.

2024-06-19 05:28 UTC, Calm-Rock commented on data/docs/userguide/send-metrics-cloud.mdx
> +The OTLP receiver accepts data through gRPC or HTTP in the <a href = "https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/specification.md" rel="noopener noreferrer nofollow" target=
```suggestion
The OTLP receiver accepts data through gRPC or HTTP in the <a href = "https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/specification.md" rel="noopener noreferrer nofollow" target="_blank" >OTLP</a> format. 
```

2024-06-19 05:28 UTC, Calm-Rock commented on data/docs/userguide/send-metrics-cloud.mdx
> +You can find more details on advanced configurations <a href = "https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/README.md" rel="noopener noreferrer nofollow"
To see more configuration options for otlp receiver, you can checkout [this link](https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/README.md)

2024-06-19 05:28 UTC, Calm-Rock commented on data/docs/userguide/send-metrics-cloud.mdx
> +- **Processors:** Metrics data is processed using the **`batch`** processor. This processor likely batches metrics before exporting them, optimizing the data flow.
```suggestion
- **Processors:** Metrics data is processed using the **`batch`** processor. This processor batches metrics before exporting them, optimizing the data flow.
```

2024-06-19 05:28 UTC, Calm-Rock commented on data/docs/userguide/send-metrics-cloud.mdx
> +- **Exporters:** Metrics processed through this pipeline are exported to the OTLP destination. The **`otlp`** exporter sends data to an endpoint specified in the configuration.
```suggestion
- **Exporters:** Metrics processed through this pipeline are exported to the OTLP endpoint mentioned in the configuration file. 
```

2024-06-19 17:06 UTC, nitishfy commented on data/docs/userguide/send-metrics-cloud.mdx
> +Data collection in OpenTelemetry Collector is facilitated through receivers. Receivers are configured via YAML under the top-level `receivers` tag. To ensure a valid configuration, at least one recei
gotcha!

2024-06-20 06:37 UTC, Calm-Rock approved these changes

2024-06-20 06:41 UTC, merged