fix: migration guide added for logs data migration
SigNoz/signoz.io pull request #849
Opened 2024-10-07 12:26 UTC by nityanandagohain

migration guide added for logs data migration

2024-10-07 12:32 UTC, Calm-Rock requested changes

2024-10-07 12:32 UTC, Calm-Rock commented on data/docs/operate/migration/upgrade-0.55.mdx
> +For migrating the data data you will need to get start and end timestamp which is the duration of logs data that you want to migrate from the old table to the new table.
```suggestion
For migrating the data you will need to get the start and end timestamp which is the duration of logs data that you want to migrate from the old table to the new table.
```

2024-10-07 12:32 UTC, Calm-Rock commented on data/docs/operate/migration/upgrade-0.55.mdx
> +In case of failure and have to run again,
```suggestion
In case of failure and you have to run the script again, 
```

2024-10-07 12:32 UTC, Calm-Rock commented on data/docs/operate/migration/upgrade-0.55.mdx
> +In case of failure and have to run again,
```suggestion
In case of failure and you have to run the script again, 
```

2024-10-07 12:32 UTC, Calm-Rock commented on data/docs/operate/migration/upgrade-0.55.mdx
> +If you face any issue, reach out to us at [Slack](https://signoz.io/slack).
```suggestion
If you face any issue, reach out to us on [Slack](https://signoz.io/slack).
```

2024-10-07 17:59 UTC, Calm-Rock approved these changes

2024-10-07 19:03 UTC, prashant-shahi reviewed
left few comments - mostly formatting

2024-10-07 19:03 UTC, prashant-shahi commented on data/docs/operate/migration/upgrade-0.55.mdx
> +        - "-dest_host=my-release-clickhouse"
Replace `my-release` with `<RELEASE>`

2024-10-07 19:03 UTC, prashant-shahi commented on data/docs/operate/migration/upgrade-0.55.mdx
> +  ```
```suggestion
  ```sql
```

2024-10-07 19:03 UTC, prashant-shahi commented on data/docs/operate/migration/upgrade-0.55.mdx
> +In case of failure and you have to run the script again,
```suggestion
In case of any failure, you have to run the script again with updated ending timestamp.
```

2024-10-07 19:03 UTC, prashant-shahi commented on data/docs/operate/migration/upgrade-0.55.mdx
> +```
```suggestion
```yaml
```

2024-10-07 19:03 UTC, prashant-shahi commented on data/docs/operate/migration/upgrade-0.55.mdx
> +* **batch_size** is the size of the batches that will be written to the new table
This section  seems to be redundant across Docker and Kubernetes.
Can this be moved to a single section? If not, at least a shared template?

2024-10-07 19:03 UTC, prashant-shahi commented on data/docs/operate/migration/upgrade-0.55.mdx
> +In case of failure and you have to run the script again,
```suggestion
In case of any failure, you have to run the script again with updated ending timestamp.
```

2024-10-07 19:03 UTC, prashant-shahi commented on data/docs/operate/migration/upgrade-0.55.mdx
> +  ```
```suggestion
```sql
```

2024-10-07 19:03 UTC, prashant-shahi commented on data/docs/operate/migration/upgrade-0.55.mdx
> +
include instructions to create pod using the yaml.

```suggestion

Now, create the `signoz-migrate-data` pod using the YAML:

```yaml
kubectl -n <NAMESPACE> apply -f pod.yaml
```

```

2024-10-07 19:03 UTC, prashant-shahi commented on data/docs/operate/migration/upgrade-0.55.mdx
> +## Migrate Data From Old Table to New Table.
```suggestion
## Migrate Data from Old Table to New Table
```

- capitalisation of `from` not needed
- no period at end

2024-10-08 04:43 UTC, nityanandagohain commented
Have made the changes @prashant-shahi

2024-10-08 07:08 UTC, prashant-shahi commented on data/docs/operate/migration/upgrade-0.55.mdx
> +  Incase you find empty response for the above query, please make sure that you upgraded to version `>=0.53` first.
```suggestion
  In case of empty response from the above query, please make sure that you upgraded to version `>=0.53` first.
```

2024-10-08 07:08 UTC, prashant-shahi commented on data/docs/operate/migration/upgrade-0.55.mdx
> +  Incase you find empty response for the above query, please make sure that you upgraded to version `>=0.53` first.
```suggestion
  In case of empty response from the above query, please make sure that you upgraded to version `>=0.53` first.
```

2024-10-08 07:09 UTC, prashant-shahi approved these changes

2024-10-08 08:02 UTC, merged