feat: add metrics doc for confluent cloud
SigNoz/signoz.io pull request #959
Opened 2024-11-10 15:20 UTC by shrutimantri

2024-11-11 00:14 UTC, shivanshuraj1333 commented
Thanks would review it when I get a breather.

2024-11-11 00:15 UTC, shivanshuraj1333 commented
@Calm-Rock kindly take a look from docs perspective when you've time.

2024-11-11 12:08 UTC, Calm-Rock requested changes

2024-11-11 12:08 UTC, Calm-Rock commented on data/docs/messaging-queues/confluent-kafka.mdx
> +and maintaining Kafka clusters.Confluent Cloud offers a fully managed, scalable, and highly available event
```suggestion
and maintaining Kafka clusters. Confluent Cloud offers a fully managed, scalable, and highly available event 
```

2024-11-11 12:08 UTC, Calm-Rock commented on data/docs/messaging-queues/confluent-kafka.mdx
> +Confluent Kafka comes with two offerings: Confluent Cloud and Confluent Platform.
```suggestion
Confluent Kafka comes with two offerings: **Confluent Cloud** and **Confluent Platform**.
```

2024-11-11 12:08 UTC, Calm-Rock commented on data/docs/messaging-queues/confluent-kafka.mdx
> +Confluent Platform, on the other hand, is a self-managed offering having a specialized distribution of Kafka
Confluent Platform is a self-managed distribution of Apache Kafka that offers enhanced features and APIs beyond the open-source version. Organizations can deploy and maintain Confluent Platform on their own infrastructure, giving them complete control over their environment. Since it builds upon Apache Kafka's core capabilities, Confluent Platform supports all Kafka use cases.

2024-11-11 12:08 UTC, Calm-Rock commented on data/docs/messaging-queues/confluent-kafka.mdx
> +---
```suggestion

```

2024-11-11 12:08 UTC, Calm-Rock commented on data/docs/messaging-queues/confluent-kafka.mdx
> +On the **Create API key -> Account** page, select **My account** and click on **Next**.
Add a note below this explaining when a user should use should use Service account.

2024-11-11 12:08 UTC, Calm-Rock commented on data/docs/messaging-queues/confluent-kafka.mdx
> +```
```suggestion
```yaml
```

2024-11-11 12:08 UTC, Calm-Rock commented on data/docs/messaging-queues/confluent-kafka.mdx
> +Depending on the choice of your region for SigNoz cloud, the otlp endpoint will vary according to this table.
Can you remove the table below and hyperlink to https://signoz.io/docs/ingestion/signoz-cloud/overview/

This doc explains about the endpoints.

2024-11-11 12:08 UTC, Calm-Rock commented on data/docs/messaging-queues/confluent-kafka.mdx
> +<TabItem value="confluent-cloud" label="Confluent Cloud" default>
Let's comment out the confluent Cloud tab for now until the schema is changed to support this format.

2024-11-11 12:08 UTC, Calm-Rock commented on data/docs/messaging-queues/confluent-kafka.mdx
> +```
Please add a note saying that replace `7.7.1` with the version that you downloaded.

2024-11-11 12:08 UTC, Calm-Rock commented on data/docs/messaging-queues/confluent-kafka.mdx
> +Depending on the choice of your region for SigNoz cloud, the otlp endpoint will vary according to this table.
Can you remove the table below and hyperlink to https://signoz.io/docs/ingestion/signoz-cloud/overview/

This doc explains about the endpoints.

2024-11-12 07:27 UTC, Calm-Rock approved these changes

2024-11-12 08:19 UTC, yuvraajsj18 approved these changes

2024-11-12 08:44 UTC, merged